#!/system/bin/sh

grep -oE 'init_[0-9_]+' /vendor/etc/selinux/nonplat_sepolicy.cil | \
	uniq | \
	sort -n | \
	head -n 1 | \
	sed -E 's/.*init_([0-9]+).*/\1/g' | \
while read version;do
	setprop persist.sys.vndk $version
done

if [ -d /sys/module/five ];then
	if mount -o bind /mnt/phh/empty /sbin/adbd;then
		setprop sys.phh.five true
	fi
elif [ -f /sbin/adbd ];then
	mount -o bind /system/bin/adbd /sbin/adbd
fi

if getprop ro.hardware |grep -qiE -e qcom -e judyln -e judypn;then
	FOUND_QCOM=1
    if getprop ro.vendor.build.fingerprint |grep -qiE '^samsung';then 
        setprop persist.sys.overlay.devinputjack false
    else
        setprop persist.sys.overlay.devinputjack true
    fi
fi
